# Forces new Travis-CI Infrastructure
sudo: false

language: php

env:
  global:
    - RUN_PHPCS="no"
    - INSTALL_MEMCACHED="yes"
    - INSTALL_REDIS="yes"

matrix:
  include:
    - php: 5.3
      env: INSTALL_APC="yes"
    - php: 5.4
      env: INSTALL_APC="yes"
    - php: 5.5
      env: INSTALL_APCU_STABLE="yes"
    - php: 5.6
      env: RUN_PHPCS="yes" INSTALL_APCU_STABLE="yes"
    - php: 7.0
      env: INSTALL_APCU_BETA="yes" INSTALL_MEMCACHED="no" INSTALL_REDIS="no"

services:
  - memcached
  - redis-server

before_script:
  # Make sure all dev dependencies are installed
  - composer install
  # Set up databases for testing
  - mysql -e 'create database joomla_ut;'
  - mysql joomla_ut < tests/unit/schema/mysql.sql
  - psql -c 'create database joomla_ut;' -U postgres
  - psql -d joomla_ut -a -f tests/unit/schema/postgresql.sql
  # Set up Apache
  # - ./build/travis/php-apache.sh
  # Enable additional PHP extensions
  - if [ "$INSTALL_MEMCACHED" == "yes" ]; then phpenv config-add build/travis/phpenv/memcached.ini; fi
  - if [ "$INSTALL_APC" == "yes" ]; then phpenv config-add build/travis/phpenv/apc-$TRAVIS_PHP_VERSION.ini; fi
  - if [ "$INSTALL_APCU_STABLE" == "yes" ]; then printf "\n" | pecl install apcu; fi
  - if [ "$INSTALL_APCU_BETA" == "yes" ]; then printf "\n" | pecl install apcu-beta; fi
  - if [ "$INSTALL_REDIS" == "yes" ]; then phpenv config-add build/travis/phpenv/redis.ini; fi

script:
  - libraries/vendor/bin/phpunit --configuration travisci-phpunit.xml
  - if [ "$RUN_PHPCS" == "yes" ]; then libraries/vendor/bin/phpcs --report=full --extensions=php -p --standard=build/phpcs/Joomla .; fi

branches:
  except:
    - 2.5.x
